---
- name: Keycloak Signup container
  docker_container:
    state: started
    name: "keycloak-signup"
    image: "{{ keycloak_signup_docker_image }}"
    restart_policy: unless-stopped
    log_driver: json-file
    log_options:
      max-size: "100m"
    labels: "{{ keycloak_signup_docker_labels }}"
    networks:
      - name: "{{ keycloak_signup_docker_network }}"
    env:
      DATABASE_NAME: "{{ keycloak_signup_database_name }}"
      DATABASE_PASSWORD: "{{ keycloak_signup_database_password }}"
      DATABASE_PORT: "{{ keycloak_signup_database_port }}"
      DATABASE_USER: "{{ keycloak_signup_database_user }}"
      DATABASE_HOST: "{{ keycloak_signup_database_host }}"
      KEYCLOAK_BASE_URL: "{{ keycloak_signup_keycloak_base_url }}"
      KEYCLOAK_CLIENT_ID: "{{ keycloak_signup_keycloak_client_id }}"
      KEYCLOAK_PASSWORD: "{{ keycloak_signup_keycloak_password }}"
      KEYCLOAK_REALM: "{{ keycloak_signup_keycloak_realm }}"
      KEYCLOAK_USERNAME: "{{ keycloak_signup_keycloak_username }}"
      KEYCLOAK_SIGNUP_SECRET_TOKEN: "{{ keycloak_signup_secret_token }}"

